# Generated by Django 5.1.6 on 2026-02-02 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Email/Phone verified via OTP'),
        ),
        migrations.CreateModel(
            name='OTPVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_e164', models.CharField(blank=True, db_index=True, max_length=20)),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254)),
                ('otp_code', models.CharField(max_length=6)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('verified', 'Verified'), ('expired', 'Expired')], default='pending', max_length=10)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('max_attempts', models.PositiveSmallIntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['phone_e164', 'status'], name='accounts_ot_phone_e_ce1cae_idx'), models.Index(fields=['email', 'status'], name='accounts_ot_email_344e89_idx'), models.Index(fields=['created_at'], name='accounts_ot_created_dffff8_idx')],
            },
        ),
    ]
