# Generated by Django 5.1.6 on 2026-02-02 05:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sos', '0003_rename_sos_sosrequest_priority_status_idx_sos_sosrequ_priorit_5604ca_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DonationTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_status', models.CharField(choices=[('agreed', 'Agreed to Donate'), ('traveling', 'Traveling to Location'), ('arrived', 'Arrived at Location'), ('donating', 'Donation in Progress'), ('completed', 'Donation Completed'), ('cancelled', 'Cancelled')], default='agreed', max_length=16)),
                ('current_latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('current_longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('estimated_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('agreed_at', models.DateTimeField(auto_now_add=True)),
                ('traveling_at', models.DateTimeField(blank=True, null=True)),
                ('arrived_at', models.DateTimeField(blank=True, null=True)),
                ('donating_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sos_response', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='donation_tracker', to='sos.sosresponse')),
            ],
            options={
                'indexes': [models.Index(fields=['sos_response', 'current_status'], name='sos_donatio_sos_res_d913f7_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_name', models.CharField(blank=True, max_length=120)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('contact_email', models.EmailField(blank=True, max_length=254)),
                ('relationship', models.CharField(help_text='e.g., Family, Friend, Caregiver', max_length=50)),
                ('can_create_sos', models.BooleanField(default=True)),
                ('can_view_medical_info', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contact_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contact_for', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'indexes': [models.Index(fields=['user', 'is_active'], name='sos_emergen_user_id_80f2ec_idx')],
                'unique_together': {('user', 'contact_user')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_template_message', models.BooleanField(default=False)),
                ('template_type', models.CharField(blank=True, choices=[('on_my_way', 'On My Way'), ('arrived', 'Arrived'), ('need_directions', 'Need Directions'), ('thank_you', 'Thank You')], max_length=32)),
                ('is_read', models.BooleanField(default=False)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('sos_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='sos.sosrequest')),
            ],
            options={
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['sender', 'recipient', '-created_at'], name='sos_message_sender__d1170e_idx'), models.Index(fields=['sos_request', '-created_at'], name='sos_message_sos_req_e0f89c_idx')],
            },
        ),
    ]
